### PR TITLE
feat: show the extended hardware info

### PR DESCRIPTION
**Pull request by lion7**
Display the extendend hardware information that was added via https://github.com/siderolabs/sidero/pull/735 in the Theila UI

Signed-off-by: Gerard de Leeuw <gdeleeuw@leeuwit.nl>

### CODE REVIEW

**Review by Unix4ever — COMMENTED** [review]
I wonder if we can hide all this detailed information under a popup that shows when you hover some (i) icon or something :thinking:
Don't quite like how big it becomes.
Also I think it's better to hide `Labels` if there are no labels.

**Comment by Unix4ever** [comment]
image
something like this I think

**Comment by andrewrynhard** [comment]
> image
> something like this I think

Yeah I like this idea.

**Comment by Unix4ever** [comment]
The new version of the UI looks cool, I wanted to do a couple adjustments there, but there are other issues here.
I see that you've updated `servers` to use `v1alpha2`, but that breaks all old cluster compatibility. 
Also we shouldn't show this additional information menu for older clusters.

I think that's the right moment to add support for getting resources without version, though I need to think a bit more how to implement it properly.,

**Comment by Unix4ever** [comment]
I've made couple of modification to make the UI a bit more consistent, and used another component for the popup.
Also, I've rebased the PR on top of my changes for versionless requests of resources, so now it should be backward and forward compatible.

**Review by Unix4ever — APPROVED** [review]

**Comment by Unix4ever** [comment]
Thanks for your contribution! :)

**Pull request merged**
